# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quizscreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QuizScreen(object):
    def setupUi(self, QuizScreen):
        QuizScreen.setObjectName("QuizScreen")
        QuizScreen.resize(1920, 1080)
        QuizScreen.setMaximumSize(QtCore.QSize(1920, 1080))
        QuizScreen.setStyleSheet("background-color: rgb(47, 85, 151);")
        self.centralwidget = QtWidgets.QWidget(QuizScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.option1Button = QtWidgets.QPushButton(self.centralwidget)
        self.option1Button.setGeometry(QtCore.QRect(580, 650, 401, 131))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.option1Button.setFont(font)
        self.option1Button.setStyleSheet("background-color: rgb(3, 193, 161);\n"
"border-radius: 25px;")
        self.option1Button.setObjectName("option1Button")
        self.option2Button = QtWidgets.QPushButton(self.centralwidget)
        self.option2Button.setGeometry(QtCore.QRect(1000, 650, 401, 131))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.option2Button.setFont(font)
        self.option2Button.setStyleSheet("background-color: rgb(3, 193, 161);\n"
"border-radius: 25px;")
        self.option2Button.setObjectName("option2Button")
        self.option3Button = QtWidgets.QPushButton(self.centralwidget)
        self.option3Button.setGeometry(QtCore.QRect(580, 790, 401, 131))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.option3Button.setFont(font)
        self.option3Button.setStyleSheet("background-color: rgb(3, 193, 161);\n"
"border-radius: 25px;")
        self.option3Button.setObjectName("option3Button")
        self.option4Button = QtWidgets.QPushButton(self.centralwidget)
        self.option4Button.setGeometry(QtCore.QRect(1000, 790, 401, 131))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.option4Button.setFont(font)
        self.option4Button.setStyleSheet("background-color: rgb(3, 193, 161);\n"
"border-radius: 25px;")
        self.option4Button.setObjectName("option4Button")
        self.homeButton = QtWidgets.QPushButton(self.centralwidget)
        self.homeButton.setGeometry(QtCore.QRect(920, 950, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.homeButton.setFont(font)
        self.homeButton.setStyleSheet("background-color: rgb(3, 193, 161);\n"
"border-radius: 25px;")
        self.homeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Developer/Swansea Uni/Project/Code/home-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeButton.setIcon(icon)
        self.homeButton.setIconSize(QtCore.QSize(40, 50))
        self.homeButton.setObjectName("homeButton")
        self.questionLabel = QtWidgets.QLabel(self.centralwidget)
        self.questionLabel.setGeometry(QtCore.QRect(50, 270, 1801, 341))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.questionLabel.setFont(font)
        self.questionLabel.setStyleSheet("background-color: white;")
        self.questionLabel.setObjectName("questionLabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(650, 10, 631, 231))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Developer/Swansea Uni/Project/Code/quiz title.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        QuizScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(QuizScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 22))
        self.menubar.setObjectName("menubar")
        QuizScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(QuizScreen)
        self.statusbar.setObjectName("statusbar")
        QuizScreen.setStatusBar(self.statusbar)

        self.retranslateUi(QuizScreen)
        QtCore.QMetaObject.connectSlotsByName(QuizScreen)

    def retranslateUi(self, QuizScreen):
        _translate = QtCore.QCoreApplication.translate
        QuizScreen.setWindowTitle(_translate("QuizScreen", "MainWindow"))
        self.option1Button.setText(_translate("QuizScreen", "Option 1"))
        self.option2Button.setText(_translate("QuizScreen", "Option 2"))
        self.option3Button.setText(_translate("QuizScreen", "Option 3"))
        self.option4Button.setText(_translate("QuizScreen", "Option 4"))
        self.questionLabel.setText(_translate("QuizScreen", "Question"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QuizScreen = QtWidgets.QMainWindow()
    ui = Ui_QuizScreen()
    ui.setupUi(QuizScreen)
    QuizScreen.show()
    sys.exit(app.exec_())
