# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'learningzoneupdate.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_self(object):
    def setupUi(self):
        self.setObjectName("self")
        self.resize(1158, 770)
        self.setMinimumSize(QtCore.QSize(1158, 770))
        self.setStyleSheet("background-color: rgb(47, 85, 151);")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        self.setup_webview()
        
        
        
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        
        self.freePlayButton = QtWidgets.QPushButton(self)
        self.freePlayButton.setMinimumSize(QtCore.QSize(211, 71))
        self.freePlayButton.setMaximumSize(QtCore.QSize(211, 71))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.freePlayButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.freePlayButton.setFont(font)
        icon1 = QIcon()
        icon1.addPixmap(QPixmap(self.current_path+"/Code/Project/Images/play-circle-regular.svg"),
                        QIcon.Normal, QIcon.Off)
        self.freePlayButton.setIcon(icon1)
        self.freePlayButton.setIconSize(QSize(60, 60))
        self.freePlayButton.setFont(font)
        self.freePlayButton.setStyleSheet("background-color: rgb(3, 193, 161);\n"
"border-radius: 15px;")
        self.freePlayButton.setObjectName("freePlayButton")
        self.gridLayout.addWidget(self.freePlayButton, 0, 2, 1, 1)
        
        # Home Button
        self.homeButton = QtWidgets.QPushButton(self)
        self.homeButton.setMinimumSize(QtCore.QSize(121, 71))
        self.homeButton.setStyleSheet("background-color: rgb(3, 193, 161);\n"
                                      "border-radius: 15px;")
        self.homeButton.setText("")
        icon = QIcon()
        icon.addPixmap(QPixmap(self.current_path+"/Code/Project/Images/home-solid.svg"),
                       QIcon.Normal, QIcon.Off)
        self.homeButton.setIcon(icon)
        self.homeButton.setIconSize(QSize(50, 60))
        self.homeButton.setObjectName("homeButton")
        self.gridLayout.addWidget(self.homeButton, 0, 1, 1, 1)
        
        # Quiz Button
        self.quizButton = QtWidgets.QPushButton(self)
        self.quizButton.setMinimumSize(QtCore.QSize(121, 71))
        self.quizButton.setMaximumSize(QtCore.QSize(121, 71))
        self.quizButton.setStyleSheet("background-color: rgb(3, 193, 161);\n"
"border-radius: 15px;")
        self.quizButton.setText("")
        icon2 = QIcon()
        icon2.addPixmap(QPixmap(self.current_path+"/Code/Project/Images/Screenshot 2020-06-26 at 11.46.35.png"),
                        QIcon.Normal, QIcon.Off)
        self.quizButton.setIcon(icon2)
        self.quizButton.setIconSize(QSize(60, 60))
        self.quizButton.setObjectName("quizButton")
        self.gridLayout.addWidget(self.quizButton, 0, 3, 1, 1)
        
        
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "Data Splash! - Learning Zone"))
        self.freePlayButton.setText(_translate("self", "Free"))

    def setup_webview(self):
        self.webView = QWebEngineView(self.centralwidget)
        self.webView.setGeometry(QRect(20, 20, 1871, 921))
        self.webView.setObjectName("widget")
        self.webView.setStyleSheet("border-radius: 15px;")
        self.webView.setUrl(self.url(self.topic))
        self.verticalLayout.addWidget(self.webView)
        self.webView.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    self = QtWidgets.QWidget()
    ui = Ui_self()
    ui.setupUi()
    self.show()
    sys.exit(app.exec_())
