# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'freeplayscreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from views.mplwidget import MplWidget
import sys
import os
import random
import numpy as np
from matplotlib.backends.backend_qt5agg import (
    NavigationToolbar2QT as NavigationToolbar)


class FreePlay(QtWidgets.QWidget):
    switch_window = QtCore.pyqtSignal(str)
    current_path = os.getcwd()

    def __init__(self):
        QtWidgets.QWidget.__init__(self)
        self.setupUi()

    def setupUi(self):
        self.setObjectName("Form")
        self.resize(1920, 1080)
        self.setStyleSheet("background-color: rgb(47, 85, 151);\n"
"")
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(600, 20, 781, 181))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(
            self.current_path+"/Code/Project/Images/freeplay.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        
        # Matplotlib Widget
        self.MplWidget = MplWidget(self) # Here is the MPLWidget
        self.MplWidget.setGeometry(QtCore.QRect(80, 240, 731, 421))
        self.MplWidget.setObjectName("MplWidget")
        
        # Group bow
        self.groupBox = QtWidgets.QGroupBox(self)
        self.groupBox.setGeometry(QtCore.QRect(80, 690, 1761, 351))
        self.groupBox.setStyleSheet("background-color: rgb(193,192,44);\n")
        self.groupBox.setObjectName("groupBox")
        
        
        self.playButton = QtWidgets.QPushButton(self.groupBox)
        self.playButton.setGeometry(QtCore.QRect(1650, 140, 101, 61))
        self.playButton.setStyleSheet("background-color: rgb(3,193,161);\n"
                                      "border-radius:15px;")
        self.playButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
            self.current_path+"/Code/Project/Images/play-circle-regular.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon)
        self.playButton.setIconSize(QtCore.QSize(40, 40))
        self.playButton.setObjectName("playButton")
        
        # Clear Button
        self.clearButton = QtWidgets.QPushButton(self.groupBox)
        self.clearButton.setGeometry(QtCore.QRect(1650, 210, 101, 61))
        self.clearButton.setStyleSheet("background-color: rgb(3,193,161);\n"
                                       "border-radius:15px;")
        self.clearButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(
            self.current_path+"/Code/Project/Images/times-circle-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearButton.setIcon(icon1)
        self.clearButton.setIconSize(QtCore.QSize(40, 40))
        self.clearButton.setObjectName("clearButton")
        
        # Home Button
        self.homeButton = QtWidgets.QPushButton(self.groupBox)
        self.homeButton.setGeometry(QtCore.QRect(1651, 281, 101, 61))
        self.homeButton.setStyleSheet("background-color: rgb(3,193,161);\n"
                                      "border-radius:15px;")
        self.homeButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(
            self.current_path+"/Code/Project/Images/home-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeButton.setIcon(icon2)
        self.homeButton.setIconSize(QtCore.QSize(40, 30))
        self.homeButton.setObjectName("homeButton")
        
        # Additional Text
        self.textFrame = QtWidgets.QFrame(self)
        self.textFrame.setGeometry(QtCore.QRect(860, 240, 981, 421))
        self.textFrame.setStyleSheet("background-color: white;\n"
"")
        self.textFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textFrame.setObjectName("textFrame")
        self.label_2 = QtWidgets.QLabel(self.textFrame)
        self.label_2.setGeometry(QtCore.QRect(120, 50, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.modelTypeLabel = QtWidgets.QLabel(self.textFrame)
        self.modelTypeLabel.setGeometry(QtCore.QRect(220, 50, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setItalic(True)
        self.modelTypeLabel.setFont(font)
        self.modelTypeLabel.setObjectName("modelTypeLabel")
        self.label_3 = QtWidgets.QLabel(self.textFrame)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.learningTypeLabel = QtWidgets.QLabel(self.textFrame)
        self.learningTypeLabel.setGeometry(QtCore.QRect(220, 10, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setItalic(True)
        self.learningTypeLabel.setFont(font)
        self.learningTypeLabel.setObjectName("learningTypeLabel")
        self.label_4 = QtWidgets.QLabel(self.textFrame)
        self.label_4.setGeometry(QtCore.QRect(70, 80, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.overviewLabel = QtWidgets.QLabel(self.textFrame)
        self.overviewLabel.setGeometry(QtCore.QRect(220, 90, 701, 261))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.overviewLabel.setFont(font)
        self.overviewLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.overviewLabel.setObjectName("overviewLabel")

        # Button Connects
        self.playButton.clicked.connect(self.update_graph)
        self.homeButton.clicked.connect(self.home_pressed)


        self.retranslateUi()
        

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Data Splash! - Free Play"))
        self.groupBox.setTitle(_translate("Form", "Model Options:"))
        self.label_2.setText(_translate("Form", "Model:"))
        self.modelTypeLabel.setText(_translate("Form", "K-Means"))
        self.label_3.setText(_translate("Form", "Learning Type:"))
        self.learningTypeLabel.setText(_translate("Form", "Unsupervised Learning"))
        self.label_4.setText(_translate("Form", "Overview:"))
        self.overviewLabel.setText(_translate("Form", "Model Overview"))

    def update_graph(self):

        fs = 500
        f = random.randint(1, 100)
        ts = 1/fs
        length_of_signal = 100
        t = np.linspace(0, 1, length_of_signal)

        cosinus_signal = np.cos(2*np.pi*f*t)
        sinus_signal = np.sin(2*np.pi*f*t)

        self.MplWidget.canvas.axes.clear()
        self.MplWidget.canvas.axes.plot(t, cosinus_signal)
        self.MplWidget.canvas.axes.plot(t, sinus_signal)
        self.MplWidget.canvas.axes.legend(
            ('cosinus', 'sinus'), loc='upper right')
        self.MplWidget.canvas.axes.set_title('Cosinus - Sinus Signal')
        self.MplWidget.canvas.draw()

    def home_pressed(self):
        self.switch_window.emit("mainmenu,freeplay")


